### ISSUE TITLE
Waiting for pool to drain warnings and hanging

### ISSUE THREAD

**Issue by eregon** [socketry/async-http-faraday#16]
Hello,

I'm trying to use this gem to speed up accessing statuses of build jobs on TravisCI.

A good example where concurrency would be valuable is [freerange/mocha](https://travis-ci.org/github/freerange/mocha/builds/673519036) which hash 60+ jobs so if we're doing 60 blocking connections it's slow (like 40+s).

The TravisCI Ruby client uses Faraday and Typhoeus by default.
Typhoeus has support for concurrency, but it doesn't seem easy to integrate to https://github.com/typhoeus/typhoeus#making-parallel-requests and seems callback-based.

So I was trying out this gem to see if it helps.

Repro code:
```ruby
require 'travis/client'
require 'async/http/faraday'
require 'async'
require 'async/barrier'
require 'async/semaphore'

session = Travis::Client::Session.new
session.faraday_adapter = :async_http

configs = []

Async::Reactor.run do
  repo = session.find_one(Travis::Client::Repository, 'guard/listen')
  build = repo.last_on_branch('master')

  barrier = Async::Barrier.new
  semaphore = Async::Semaphore.new(3, parent: barrier)

  build.job_ids.each do |job_id|
    semaphore.async do
      puts "Starting #{Async::Task.current}"
      j = session.find_one(Travis::Client::Job, job_id)
      p j.config
      configs << j.config
    end
  end

  barrier.wait
  puts "After WAIT"
end

p configs
```

That seems to mostly work, except it hangs at the end and emits multiple warnings:
```
$ ruby test.rb
Starting #<Async::Task:0x2af901fbaffc (running)>
Starting #<Async::Task:0x2af901fc1668 (running)>
Starting #<Async::Task:0x2af901fc06b4 (running)>
 2.28s     warn: Async::HTTP::Client [oid=0x2af901fba228] [pid=11494] [2020-04-12 14:54:46 +0200]
               | Waiting for pool to drain: #<Async::Pool::Controller(1/∞) 2/128/3>
{"os"=>"linux", "rvm"=>2.4, "dist"=>"xenial", "cache"=>"bundler", "group"=>"stable", ".result"=>"configured", "language"=>"ruby"}
Starting #<Async::Task:0x2af902200780 (running)>
 2.35s     warn: Async::HTTP::Client [oid=0x2af901fba228] [pid=11494] [2020-04-12 14:54:46 +0200]
               | Waiting for pool to drain: #<Async::Pool::Controller(1/∞) 1/128/3>
{"os"=>"linux", "rvm"=>2.5, "dist"=>"xenial", "cache"=>"bundler", "group"=>"stable", ".result"=>"configured", "language"=>"ruby"}
Starting #<Async::Task:0x2af9021b11a8 (running)>
{"os"=>"linux", "rvm"=>2.3, "dist"=>"xenial", "cache"=>"bundler", "group"=>"stable", ".result"=>"configured", "language"=>"ruby"}
Starting #<Async::Task:0x2af9021b2788 (running)>
 2.99s     warn: Async::HTTP::Client [oid=0x2af9021b06b8] [pid=11494] [2020-04-12 14:54:47 +0200]
               | Waiting for pool to drain: #<Async::Pool::Controller(1/∞) 2/128/2>
{"os"=>"linux", "rvm"=>"jruby", "dist"=>"xenial", "cache"=>"bundler", "group"=>"stable", ".result"=>"configured", "language"=>"ruby"}
Starting #<Async::Task:0x2af90227e090 (running)>
 3.05s     warn: Async::HTTP::Client [oid=0x2af9021b06b8] [pid=11494] [2020-04-12 14:54:47 +0200]
               | Waiting for pool to drain: #<Async::Pool::Controller(1/∞) 1/128/2>
{"os"=>"osx", "env"=>"LISTEN_TESTS_DEFAULT_LAG=2", "rvm"=>2.6, "cache"=>"bundler", ".result"=>"configured", "language"=>"ruby"}
Starting #<Async::Task:0x2af9021e0b10 (running)>
{"os"=>"linux", "rvm"=>2.6, "dist"=>"xenial", "cache"=>"bundler", "group"=>"stable", ".result"=>"configured", "language"=>"ruby"}
 3.62s     warn: Async::HTTP::Client [oid=0x2af9021e0020] [pid=11494] [2020-04-12 14:54:48 +0200]
               | Waiting for pool to drain: #<Async::Pool::Controller(1/∞) 1/128/1>
{"os"=>"linux", "rvm"=>"ruby-head", "dist"=>"xenial", "cache"=>"bundler", "group"=>"stable", ".result"=>"configured", "language"=>"ruby"}
{"os"=>"linux", "rvm"=>"truffleruby", "dist"=>"xenial", "cache"=>"bundler", "group"=>"stable", ".result"=>"configured", "language"=>"ruby"}
After WAIT
^CTraceback (most recent call last):
	4: from test.rb:12:in `<main>'
	3: from ruby-2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:56:in `run'
	2: from ruby-2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:234:in `run'
	1: from ruby-2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:204:in `run_once'
ruby-2.6.5/lib/ruby/gems/2.6.0/gems/async-1.24.2/lib/async/reactor.rb:204:in `select': Interrupt
```

Any idea how to fix that?

**Comment by eregon** [comment]
Maybe related to https://github.com/socketry/async-http-faraday/issues/7 and https://github.com/socketry/async-http/issues/37

**Comment by ioquatix** [comment]
You need to update faraday to 1.0 and add `session.connection.close` after `barrier.wait`.

**Comment by ioquatix** [comment]
By the way, I'm exploring ways to remove the need to call `Connection#close`, but at the moment, that's how it is.

**Comment by eregon** [comment]
> You need to update faraday to 1.0 and add `session.connection.close` after `barrier.wait`.

That would still emit the warnings before though, i.e., the warnings are as soon as a task completes it seems.

**Comment by ioquatix** [comment]
The warnings are because the connection cannot be persistent with faraday < 1.0 (no #close method), and you are running it in a context which IS persistent (i.e. to get concurrency). You end up with multiple requests using the same connection pool, until two requests try to close it. It's kind of tricky to explain, but this is the reason why and the solution will work.

The other solution is some how to avoid the need to invoke #close which means persistent connections can be used, scoped to the top level run loop (implicit close). However it's not implemented yet.

**Comment by eregon** [comment]
Excellent, thanks for creating the PRs.
Let's hope they get merged soon.

I confirm it works well with this Gemfile:
```ruby
source "https://rubygems.org"

gem 'gh', github: 'ioquatix/gh', branch: 'patch-1'
gem 'travis', github: 'ioquatix/travis.rb', branch: 'patch-1'

gem 'async-http-faraday'
```
and adding `session.connection.close`.

**Comment by ioquatix** [comment]
@olleolleolle FYI

**Comment by ioquatix** [comment]
Nice work @eregon

**Comment by eregon** [comment]
And with `freerange/mocha` and no semaphore I can get all results in ~2.5s (vs 23s with `Semaphore.new(1, ...)`) and ~40s with typhoeus. Awesome :)

**Comment by ioquatix** [comment]
Oh, one more thing, you should prefer `Async do` over `Async::Reactor.run do`. The latter is kind of janky old syntax.

**Comment by ioquatix** [comment]
Does the endpoint support HTTP/2?

**Comment by eregon** [comment]
The README mentions the later: https://github.com/socketry/async-http-faraday#usage

**Comment by ioquatix** [comment]
Can you make a PR to fix it please?

**Comment by ioquatix** [comment]
I believe this should all be fixed, can you check?

**Comment by ioquatix** [comment]
This is almost certainly fixed.
