### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by semaperepelitsa** [socketry/async-http-faraday#18]
It seems to be ignoring :proxy parameter (or http_proxy environment variable). Is this not supported?

```ruby
> Faraday.new(proxy: "http://example.com") { |f| f.adapter :async_http }.get("http://google.com").headers
=> {"Location"=>"http://www.google.com/",
 "Content-Type"=>"text/html; charset=UTF-8",
 "Date"=>"Thu, 28 May 2020 21:42:59 GMT",
 "Expires"=>"Sat, 27 Jun 2020 21:42:59 GMT",
 "Cache-Control"=>"public, max-age=2592000",
 "Server"=>"gws",
 "X-XSS-Protection"=>"0",
 "X-Frame-Options"=>"SAMEORIGIN"}

> Faraday.new(proxy: "http://example.com") { |f| f.adapter :net_http }.get("http://google.com").headers
=> {"content-type"=>"text/html", "date"=>"Thu, 28 May 2020 21:42:48 GMT", "server"=>"ECS (nyb/1D2F)", "content-length"=>"345"}
```

**Comment by ioquatix** [comment]
The underlying async-http library supports it but I don't know how faraday works. Can you point me at the documentation for how faraday expects the underlying adapters to work?

**Comment by semaperepelitsa** [comment]
I don't know if there are any guides on making custom adapters. I would just look at the official implementations and imitate what they are doing. For example, Net HTTP:
https://github.com/lostisland/faraday/blob/f6130995eb4db72a46d612f5d8e212b4dd2cf5b9/lib/faraday/adapter/net_http.rb

Since Async does persistent connections, Net HTTP Persistent adapter could also be helpful to see:
https://github.com/lostisland/faraday/blob/f6130995eb4db72a46d612f5d8e212b4dd2cf5b9/lib/faraday/adapter/net_http_persistent.rb

Proxy parameter is available in `env.request[:proxy]`, so it is expected to be customisable per request.
https://www.rubydoc.info/gems/faraday/Faraday/Env#request-instance_method

I see that Async::HTTP::Internet is used in the adapter but it does not have proxy parameters. And Async::HTTP::Proxy is a lower-level class. That means the underlying library will probably require changes before adapter support can be implemented.

**Comment by ioquatix** [comment]
Thanks for the links I will take a look.
