### ISSUE TITLE
support on_data callback

### ISSUE THREAD

**Issue by pschrammel** [socketry/async-http-faraday#22]
To e.g. downstream a file in falcon it would be cool if the adapter would support on_data callbacks. See https://lostisland.github.io/faraday/usage/streaming

**Comment by korbin** [comment]
https://github.com/angellist/async-http-faraday/commit/c47d7ea1b7f510e9cd378eac98711c27ca9489da

is how it can be done. I don't have time to add the appropriate test coverage right now to PR this, but it works.

**Comment by ioquatix** [comment]
I've released this in v0.16.0 - thanks everyone!
