### ISSUE TITLE
Configuring SSL

### ISSUE THREAD

**Issue by zhulik** [socketry/async-http-faraday#25]
Hello,

how do I configure the `async_http` adapter to use my own ssl certificate? 

Both ways  `ssl: {verify: false}` and `ssl: { ca_path: "ca.crt" }` described in [Faraday wiki](https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates) seem to be ignored. Switching to the default adapter make it work

Thank you!

**Comment by zhulik** [comment]
It turned out the default faraday adapter(net/http) plays nice with async at least on ruby 3.2. There is virtually no need in a separate async adapter

**Comment by ioquatix** [comment]
Yes, `Net::HTTP` is okay if you don't need high performance - `Async::HTTP` has better performance and persistent connections. But for general purpose, `Net::HTTP` is probably quite okay.

Regarding SSL, you'd need to modify this code to prepare an appropriate SSL context: https://github.com/socketry/async-http-faraday/blob/92e72ff77e95cd7c23a9b3cb8fc094793589b137/lib/async/http/faraday/adapter.rb#L102-L129

I'll see if I can add a test for this.
