### ISSUE TITLE
Exception on `connection.close` call

### ISSUE THREAD

**Issue by AlexWayfer** [socketry/async-http-faraday#29]
Hello.

I have simple code: `connection.close` (`connection` is an instance of Faraday).

I see your adapter has its implementation (not a lot of adapters have, as I've researched).

But I'm getting an exception, which seems internal for me:

```
0.86s     warn: Async::HTTP::Client [oid=0x170c] [ec=0x1720] [pid=90489] [2023-07-24 17:57:40 +0300]
               | Waiting for Async::HTTP::Protocol::HTTPS pool to drain: #<Async::Pool::Controller(1/∞) 1/4294967295/1>
/home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/condition.rb:38:in `block in wait': undefined method `transfer' for nil:NilClass (NoMethodError)

				Fiber.scheduler.transfer
				               ^^^^^^^^^
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/list.rb:85:in `stack'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/condition.rb:37:in `wait'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-pool-0.4.0/lib/async/pool/controller.rb:87:in `wait'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-http-0.60.2/lib/async/http/client.rb:73:in `close'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-http-faraday-0.12.0/lib/async/http/faraday/adapter.rb:82:in `each'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-http-faraday-0.12.0/lib/async/http/faraday/adapter.rb:82:in `close'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.10/lib/faraday/middleware.rb:27:in `close'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.10/lib/faraday/middleware.rb:27:in `close'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.10/lib/faraday/middleware.rb:27:in `close'
	from /home/alex/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.10/lib/faraday/connection.rb:126:in `close'
```

**Comment by ioquatix** [comment]
(1) You must close the connection within the reactor.

(2) Calling close is not required if you leave the reactor scope, it will be done automatically.

Can you check the code for when you are calling close?

**Comment by AlexWayfer** [comment]
> (1) You must close the connection within the reactor.

Sorry, I don't understand what's "the reactor".



> Can you check the code for when you are calling close?

I have simple `Signal.trap('INT')` and wanted to "abort" connection gracefully.

After creating this issue, I had a conversation with Faraday maintainers, and now it seems that `Faraday::Connection#close` works not as "abort", as I thought after reading short documentation, but more like "finish" or something, after a request.

https://github.com/lostisland/faraday-net_http/issues/32

So, if you think this behavior of your adapter is correct and exception is expected — you're free to close the issue.

**Comment by ioquatix** [comment]
Calling `Connection#close` from an interrupt handler is probably going to cause fireworks.

> the reactor

It must be within the same top level `Async{}` (or `Sync{}`) block.

If you want this level of control, use `Timeout.timeout` or call `response.close` at the appropriate point. `Response#close` will forcefully close the connection, while `Response#finish` will gracefully finish the connection (may take a long time).

**Comment by ioquatix** [comment]
Maybe you can share a short repro of what problem you are trying to solve and I can provide more feedback.

**Comment by AlexWayfer** [comment]
> Maybe you can share a short repro of what problem you are trying to solve and I can provide more feedback.

In the issue, mentioned above, there is code in my last comment, pretty short, with `Net::HTTP` request to `api.telegram.org`.

The meaning of `/getUpdates` end-point is long polling. So these requests designed to be long: response only where are actual updates, or return emptiness by timeout around 20–60 seconds (and client should make a new one).

I just wanted to abort this long request gracefully on exit signal.

**Comment by ioquatix** [comment]
Using something like `Thread#raise(Interrupt)` is safe with the event loop, if your goal is to cause it to exit. Another option might be to have a `Thread::Queue`, write to it from the interrupt handler, and read from it in a separate concurrent task. More specifically, we do have `Async::IO::Trap` which does this: https://github.com/socketry/async-io/blob/main/lib/async/io/trap.rb

**Comment by ioquatix** [comment]
I think we can close this issue as there is no action here, however feel free to create a discussion if you want to talk about trapping interrupts in more detail.

In general, I don't think Faraday provides an interface for "stopping a connection mid-flight". I'd suggest using `Async::HTTP` directly which does.
