### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by ioquatix** [socketry/async-http-faraday#35]
Imagine a vanilla rails app, where controller actions might look like:

```ruby
class SomeController < ApplicationController
  def update
    response = request_handler.do_post("https://microsoft.com/update_thing", params[:post_body])
    render json: response.body
  end

  def request_handler
    @_request_handler ||= RequestHandler.new
  end
end
```
and `RequestHandler` something like:
```ruby
class RequestHandler
  def do_post(url, body)
    task = Async do
      conn.post(url) do |req|
        req.body = body
      end
    end
    response = task.wait
  end

  def conn
    Faraday.new do |c|
      c.adapter :async_http
    end
  end
end
```
the app is using `falcon host` or `falcon virtual` with the `rack` configuration, a preload of the rails environment, and `endpoint Async::HTTP::Endpoint.parse("http://0.0.0.0:3000")`. pretty simple.

_Originally posted by @jakeonfire in https://github.com/socketry/async-http-faraday/issues/32#issuecomment-1931558678_

**Comment by ioquatix** [comment]
I believe you need to invoke `#close` on `conn` after you are done with it... Are you able to check if this solves your problem? I will also take a look on my end if I have time.

**Comment by jakeonfire** [comment]
i thought about that but it doesn't seem closeable. faraday should close the adapter automatically after every request afaik.
```
NoMethodError: undefined method `close' for #<Faraday::Connection...
```

**Comment by ioquatix** [comment]
It should be this one:

https://github.com/lostisland/faraday/blob/main/lib/faraday/connection.rb#L122-L127

**Comment by jakeonfire** [comment]
ah i'm looking at the wrong source. let me try with faraday 1.x.

**Comment by jakeonfire** [comment]
`#close` works. canarying the change in production...

would it make sense to restrict `async-http-faraday` to `faraday >= 1.0`? might help others to put a call to `close` in the README instructions, as well.

**Comment by ioquatix** [comment]
I recommend trying the

```
begin
  connection = ...
  connection.get ...
ensure
  connection.close
end
```

model to start with (as it seems you are). However, you won't get persistent connections this way.

So, after you tried that, use the `thread-local` gem: https://github.com/socketry/thread-local?tab=readme-ov-file to share an instance:

```
connection = MyConnection.instance
connection.get ...
```

Using the persistent connection will improve throughput and latency.

**Comment by jakeonfire** [comment]
getting [a different issue now](https://github.com/socketry/async-http-faraday/issues/36)

**Comment by jakeonfire** [comment]
despite the new issue, memory usage is stable, so closing the connection seems to have been the ticket 🥳

**Comment by jakeonfire** [comment]
Faraday's myriad instantiation-time configurations and state makes sharing a connection difficult. what if different requests from the same thread need different middleware?

**Comment by ioquatix** [comment]
Yeah, I understand your issue. For the sake of persistent connections, maybe we want a shared internal pool of HTTP connections. Most of the request/response processing won't actually impact the underlying connection pool...

**Comment by jakeonfire** [comment]
yeah that sounds about right. i may take a look.

**Comment by jakeonfire** [comment]
[i'd close this issue but i don't have the button for some reason]

**Comment by jakeonfire** [comment]
you can close this issue 🙂

**Comment by jakeonfire** [comment]
> Using the persistent connection will improve throughput and latency.

do you think using a process-wide connection pool instead of a thread-local one, via https://github.com/mperham/connection_pool, might be more efficient in some ways?

**Comment by ioquatix** [comment]
No, you should avoid doing additional connection pooling.

The reason is, there are life-cycle issues at play.

Using `thread-local` for your connection object is the best but... I'll try to default to the shared connection pool provided by `async-http`. Please give me a day to check it and come back to you.

**Comment by jakeonfire** [comment]
thought you should know, with `falcon` and `async-http-faraday` our servers are about 50% more efficient. using slightly more CPU and slightly more memory, but able to handle (at least) 2x the traffic with half the latency.

**Comment by ioquatix** [comment]
@jakeonfire is it okay to use your testimonial on my website?

**Comment by jakeonfire** [comment]
@ioquatix sure!
