### ISSUE TITLE
URL-encoded bodies are not readable - request errors during processing

### ISSUE THREAD

**Issue by jakeonfire** [socketry/async-http-faraday#36]
it seems setting the body to a hash for `url_encoded` requests results in a `String` body in the async faraday adapter where it is expecting a `Readable`?
```
49.64s     warn: Async::Task: Writing #<Async::HTTP::Faraday::BodyWrapper:0x0000ffffa59bc440> to #<Async::HTTP::Protocol::HTTP2::Response::Stream:0x0000ffffa758a1e0>. [oid=0x23a0] [ec=0x23b4] [pid=149] [2024-02-07 20:54:59 +0000]
               | Task may have ended with unhandled exception.
               |   NoMethodError: undefined method `read' for "foo=42":String
               |   → /usr/local/bundle/gems/async-http-faraday-0.13.0/lib/async/http/faraday/adapter.rb:34 in `read'
               |     /usr/local/bundle/gems/async-http-0.63.0/lib/async/http/protocol/http2/output.rb:83 in `passthrough'
               |     /usr/local/bundle/gems/async-2.8.1/lib/async/task.rb:161 in `block in run'
               |     /usr/local/bundle/gems/async-2.8.1/lib/async/task.rb:331 in `block in schedule'
```
code to repro:
```ruby
task = Async do
  conn = Faraday.new do |c|
    c.request :url_encoded
    c.adapter :async_http
  end
  conn.post("https://httpbin.org/post") do |req|
    req.body = {foo: 42}
  end
ensure
  conn&.close
end
task.wait
```

**Comment by ioquatix** [comment]
@imactia is there documentation about what valid `body` can be and what to do with it i.e. how to get a consistent readable interface?

**Comment by ioquatix** [comment]
https://github.com/lostisland/faraday-net_http/blob/main/lib/faraday/adapter/net_http.rb#L79-L107 has some logic for handling the body... but it will obviously depend on `Net::HTTP`'s handling.

**Comment by ioquatix** [comment]
The logic is implemented here: https://github.com/ruby/net-http/blob/8d7cfe640bad5f0114792dc991e888b9fb2e132f/lib/net/http/generic_request.rb#L198-L208

**Comment by jakeonfire** [comment]
work-around for now:
```ruby
task = Async do
  conn = Faraday.new do |c|
    c.adapter :async_http
  end
  conn.post("https://httpbin.org/post") do |req|
    req.body = StringIO.new({foo: 42}.to_query)
    req.headers[Faraday::Request::UrlEncoded::CONTENT_TYPE] ||= Faraday::Request::UrlEncoded.mime_type
  end
ensure
  conn&.close
end
task.wait
```

**Comment by ioquatix** [comment]
I think I found the solution, I'll try to make a release within a few hours of the fix.

**Comment by jakeonfire** [comment]
also seeing this with e.g.
```ruby
task = Async do
  conn = Faraday.new do |c|
    c.adapter :async_http
  end
  conn.post("https://httpbin.org/post") do |req|
    req.body = {foo: 42}.to_json
    req.headers["Content-Type"] ||= "application/json"
  end
ensure
  conn&.close
end
task.wait
```
fwiw

**Comment by ioquatix** [comment]
Do you mind trying out `v0.13.1` which was just released. It should fix the issue.

**Comment by jakeonfire** [comment]
`v0.13.1` fixes the issue 🥳 thanks!

**Comment by iMacTia** [comment]
Thank you for the quick fix @ioquatix 🙌 

I'm surprised this never happened before because to my knowledge it's fairly common for Faraday to pass a string as the request body for post/put/patch methods 🤔 

> Is there documentation about what valid body can be and what to do with it
Not really, because what the adapter expects can vary wildly. As I said though, to my knowledge, `String` is almost always what is given to the adapter (after middleware takes whatever the input is, like a `Hash` and turns that into a string).

**Comment by iMacTia** [comment]
mmmh it seems like `Net::HTTP` supports `#read` as well, but you need to pass it explicitly as [body_stream](https://docs.ruby-lang.org/en/master/Net/HTTPGenericRequest.html#method-i-body_stream-3D).

To be fair, Faraday have just recently added first-class support for RESPONSE streaming, this looks more like we want to support request body streaming. Might be a good addition to the API.

Adapters like `async-http` will support it transparently, while others like `net-http` would require some extra code

**Comment by ioquatix** [comment]
For sure it seems needed for multipart post - because that is a rich object which responds to `#read` so I'm not sure how other clients are handling it (it was simply assigned to `#body`.

**Comment by iMacTia** [comment]
Opened https://github.com/lostisland/faraday/issues/1554, thank you so much for the discussion 🙌 !
