### ISSUE TITLE
Connection problems with 0.15.0

### ISSUE THREAD

**Issue by travisbell** [socketry/async-http-faraday#39]
Hey Sam,

After upgrading to 0.15.0 we seem to be having an explosion of connections problem, to the point where the upstream service (OpenSearch) starts issuing 429's and everything just crumbles from there.

Downgrading back to 0.14.0 solves the issue.

I've been using `Thread::Local` to cache an instance of my client. This is in a Falcon environment.

With 0.15.0, I tried storing an instance of the client as a class variable since the point of 0.15.0 seems to be that the connection pool is thread safe now but there was no change. I also tried using (what I assumed to be) the original connection pool with `clients: Async::HTTP::Faraday::PersistentClients` but that also yielded no change.

For now I've locked things down to 0.14.0, if there's anything else I can provide to help, I'm happy to do so.

**Comment by ioquatix** [comment]
Hmm thanks for the report I’ll investigate.

**Comment by ioquatix** [comment]
I think the client cache is not working correctly. I've added a test for it, and it failed.

**Comment by ioquatix** [comment]
Apologies, the client cache code was simply wrong and there were not enough tests to pick up on it.

Do you mind trying the latest v0.16.0 release?

**Comment by travisbell** [comment]
Finally got back to this, upgraded and deployed and things are looking 💯.

Thanks!
