### ISSUE TITLE
Adding Protocol::HTTP::Middleware

### ISSUE THREAD

**Issue by korbin** [socketry/async-http-faraday#43]
We're currently in the process of replacing `HTTParty` and `URI.open` with `Faraday` and `Async::HTTP`.

I'd love to be able to return a substitute `Client` from https://github.com/socketry/async-http-faraday/blob/main/lib/async/http/faraday/clients.rb#L41 with my own `Protocol::HTTP::Middleware` wrappers on it.

Currently, to get at this `Client` variable and wrap it with, say, a `RelativeLocation`, a fair amount of internal interface monkey patching needs to take place.

I'd love to be able to use the output of this block instead or pass an Array of `Protocol::HTTP::Middleware`s to the adapter configuration:

```Ruby
def make_client(endpoint)
	client = Client.new(endpoint, **@options)
	@block&.call(client) || client
end
```

There may be a cleaner way to do this - this would probably break existing code without another flag or something though. (We could potentially add a `respond_to?(:call)` to heuristically test the output value for compatibility)

**Comment by ioquatix** [comment]
Yeah something like this seems reasonable to me. Can you make a PR?

**Comment by korbin** [comment]
Thank you for making this change - this is perfect! I was hoping to loop back to this but my father-in-law just passed unexpectedly - this is much appreciated work.

**Comment by ioquatix** [comment]
I'm sorry to hear that, feel free to give me some feedback when you try it out.
