### ISSUE TITLE
Support Faraday `#in_parallel` method

### ISSUE THREAD

**Issue by tmimura39** [socketry/async-http-faraday#44]
Thanks for the nice gem.
I am considering using this gem in my product.

We recognize that the parallelization of HTTP requests works only when Async and Faraday are combined in addition to using this adapter.
This was just a little more difficult.

So here is one suggestion.
Could you consider providing an in_parallel method?
This is a mechanism originally implemented by a Gem called [typhoeus](https://github.com/typhoeus/typhoeus) to serve parallel requests faraday.
https://github.com/lostisland/faraday/wiki/Parallel-requests

In addition to typhoeus, [httpx](https://github.com/HoneyryderChuck/httpx) is also supported.
https://github.com/HoneyryderChuck/httpx/blob/72786476888c73a2f94df3333d43b828d3c1c076/lib/httpx/adapters/faraday.rb#L154-L290

By utilizing this mechanism, Async control can be hidden and parallel requests can be realized.
```ruby
response1, response2 = nil

conn = Faraday.new(:url => "http://coolness.com") do |faraday|
  faraday.adapter :typhoeus
end

conn.in_parallel do
  response1 = conn.get('/one')
  response2 = conn.get('/two')
end

response1.body
response2.body
```

Unfortunately, the difficulty of implementing this is not clear to me.

If you have any thoughts, please let me know.

**Comment by ioquatix** [comment]
I investigated it, unfortunately we are blocked on <https://github.com/lostisland/faraday/issues/1583>.

```
response1 = Async{conn.get('/one')}
response2 = Async{conn.get('/two')}

response1.wait.body
response2.wait.body
```

**Comment by tmimura39** [comment]
Thanks for the comment.

Determine if in_parallel or not in each adapter, and put off the request processing.

It seems like it would be a good idea to mimic the implementation of typhoeus.
https://github.com/dleavitt/faraday-typhoeus/blob/bdfe2e3e7a3c98f857d09ce2b90163d77cb531c2/lib/faraday/adapter/typhoeus.rb#L44-L50

Sorry for the mess, but this is the image.
```ruby
require "async"
require "async/http/faraday"

module Async
  module HTTP
    module Faraday
      class Adapter < ::Faraday::Adapter
        self.supports_parallel = true

        def self.setup_parallel_manager(options = {})
          ParallelManager.new(options)
        end

        def call(env)
          super

          if parallel?(env)
            env[:parallel_manager].enqueue(env)
          else
            # original call method
          end
          @app.call(env)
        end

        private

        class ParallelManager
          def initialize(options)
            @env_list = []
            @connection_options = options
          end

          def enqueue(env)
            @env_list << env
          end

          def run
            return if @env_list.empty?

            Sync do |task|
              @env_list.map do |env|
                task.async do
                  # HTTP Request Process
                end
              end.map(&:wait)
            end
          end
        end

        def parallel?(env)
          !!env[:parallel_manager]
        end
      end
    end
  end
end

require "async/http/faraday/default"

module TestAsync
  URL = 'https://www.google.com/search'
  TOPICS = %W{ruby python lisp javascript cobol}

  def self.fetch_topics_async_in_parallel
    conn = Faraday.new(URL)
    conn.in_parallel do
      TOPICS.map do |topic|
        conn.get("?=#{topic}")
      end
    end
  end
end

TestAsync.fetch_topics_async_in_parallel
```

**Comment by ioquatix** [comment]
This looks okay to me, however I'd suggest we have a separate adapter as this is not strictly necessary to change the existing code path. For example `ParallelAdapter` which can internally use a normal `Adapter`.

I still think we should fix this in Faraday if possible. It's much better to start the connection earlier rather than later.

**Comment by tmimura39** [comment]
Understood.
I will try to create a dedicated ParallelAdapter (when I can find time to work on it).

Thanks for your comment 😄 

I am satisfied with your opinion.
You may close this issue if you do not need it.

**Comment by ioquatix** [comment]
I will keep this open for now, thanks :)

I thought about my response and your response a bit more.

If it turns out making `ParallelAdapter` is too messy, I'd be okay with modifying the current adapter implementation. I think the key point is to ensure that existing usage of `Async{adapter.get(...)}` is not impacted.

**Comment by tmimura39** [comment]
Thank you.

I think ParallelAdapter can be implemented, but I believe most of it will be copying the current adapter implementation. (Here's what's in the `#call`)

If the processing defined in the `#call` is cut out to another module, etc., it would be good to have common processing, but if we want to go that far, I think it would be better to extend the current adapter.

I would consider implementing that as well, but unfortunately I am not going to have time to work on it for a while.

If anyone is interested, please take up the challenge.
