### ISSUE TITLE
Improve connection reuse

### ISSUE THREAD

**Issue by ioquatix** [socketry/async-http-faraday#7]
https://github.com/socketry/async-http-faraday/pull/6

The connection is closed after making one request.

We should probably reuse the client.

But in order to do so, we need to hook into (or expose) some life cycle methods, namely `#close`.

I don't know if `faraday` exposes such a method.

Probably the simplest approach is to use `Async::HTTP::Internet` which maintains connection pools for each requested host. But it doesn't perform any general tidy up - i.e. close unused connections after a few minutes.

**Comment by ioquatix** [comment]
@binarycode do you want to take a stab at this?

Maybe take a look at how https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http_persistent.rb works... does anyone ever close the connection?

In the constructor for the adaptor, `@internet = Async::HTTP::Internet.new`

Then you can use `@internet.get(url, ...etc)`

Finally, maybe somewhere expose `@internet.close`.

Maybe file an upstream bug with faraday if they don't support life cycle methods.

**Comment by binarycode** [comment]
I've checked `NetHttpPersistent` adapter and it looks like they are relying on GC to clean up connections once the thread is finished. This will not work in our case, so the only way we can reuse connections that I could come up with is to implement thread-local `Async::HTTP::Client` cache with a fixed size. Every time a request is made, the adapter will take the client from the cache if present or allocate a new client in the cache otherwise. If the cache is full, the oldest client is evicted and replaced with the new one.

What do you think?

**Comment by ioquatix** [comment]
What is wrong with just using `Async::HTTP::Internet` and exposing a `close` method?

**Comment by binarycode** [comment]
Well first of all neither `Faraday::Adapter` nor `Faraday::Connection` expose any methods that can be used to close the connections, so we'll need to think of some non-standard method of doing that. But my main concern is that we're shifting responsibility of closing the connections to users, who will forget to do that and end up with leaking sockets issue. If this can be done automatically, it's better do it so.

I'll try to make a PR with my idea of client cache to see if it's a viable one.

**Comment by ioquatix** [comment]
Okay let's see how it works out.

I'm cautious of adding to the burden of global state.

If anything, I'd rather implement `#close`, get that method upstreamed into Faraday proper and use a GC finalizer to call it if the user forgot to call it.

Per thread caches are exceedingly tricky to implement correctly based on my experience looking at other gems which do it.

**Comment by ioquatix** [comment]
Sorry, just a question maybe you know, what's the thread safety guarantee of Faraday?

Do users expect to call into the faraday adapter stack from different threads and have everything work correctly?

**Comment by binarycode** [comment]
No idea about that, sorry.

**Comment by ioquatix** [comment]
You can define finalisers, not sure if you are familiar with it, but it's a hook when an object is GCed.

https://gist.github.com/dantswain/c1198e27f95664449fec#file-gistfile1-rb-L26

**Comment by ioquatix** [comment]
I thought about it and this won't work.

Async has strict requirements for scoping and life cycle. The current implementation is probably the best we can manage, and for persistent connections the only way to do it is to provide a #close method.

The reason is, for HTTP/2, there is a background reader, and the life cycle of this cannot escape the async block, except under very special circumstances.

**Comment by ioquatix** [comment]
https://github.com/lostisland/faraday/issues/241

The best thing to do would be to get this into the 1.0 interface/release.

**Comment by ioquatix** [comment]
@binarycode okay there is now a close method in faraday :)

**Comment by ioquatix** [comment]
This is now working as intended with persistent connections where possible.
